#!/bin/bash

wget -nv -nc https://machine.funklet.com/sounds/spring.wav
wget -nv -nc https://machine.funklet.com/sounds/foothat.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/hat1.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/hat2.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/hat3.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/hat4.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/ahat1.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/ahat2.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/ahat3.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/ahat4.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/ohat1.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/ohat2.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/ohat3.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/ohat4.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/aohat1.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/aohat2.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/aohat3.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/aohat4.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/snare1.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/snare2.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/snare3.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/snare4.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/asnare1.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/asnare2.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/asnare3.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/asnare4.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/kick1.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/kick2.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/kick3.wav
wget -nv -nc https://machine.funklet.com/sounds/standard/kick4.wav
